package placement;

import java.util.List;

/** Admin extends User, implements Reportable. */
public class Admin extends User implements Reportable {
    private String employeeId;

    public Admin(String id, String name, String email, String password, String employeeId) {
        super(id, name, email, password);
        this.employeeId = employeeId;
    }

    @Override
    public String getRole() {
        return "Admin";
    }

    public void scheduleDrive(String companyName, String date) {
        System.out.println("Drive scheduled for " + companyName + " on " + date);
    }

    public boolean verifyEligibility(Student student, double minCgpa) {
        return student.checkEligibility(minCgpa);
    }

    // Overrides Reportable differently from Recruiter (POLYMORPHISM - overriding)
    @Override
    public String generateReport() {
        return "Admin Report generated by employee " + employeeId;
    }

    // Overloaded version that summarises all placement records (POLYMORPHISM - overloading)
    public String generateReport(List<PlacementRecord> records) {
        StringBuilder sb = new StringBuilder("Placement Summary Report:\n");
        int placed = 0;
        for (PlacementRecord r : records) {
            sb.append("  - ").append(r).append("\n");
            if ("Placed".equalsIgnoreCase(r.getStatus())) placed++;
        }
        sb.append("Total Placed: ").append(placed).append(" / ").append(records.size());
        return sb.toString();
    }

    public String getEmployeeId() { return employeeId; }
}
